language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - lovelesh90@gmail.com